### ISSUE TITLE
How to change language from ru to en?

### ISSUE THREAD

**Issue by techroy23** [Papayaplayer/papayaplayer#2]
Sorry im new to JS I checked the file and found there is a English local in it. 
i would like to know how can i set EN as default?

EDIT : also how to hide div "status-video" when not in full screen

**Comment by Papayaplayer** [comment]
Good afternoon! Thanks for the feedback. This function is not yet available in the script. We will add it ASAP.

**Comment by Papayaplayer** [comment]
Done. It's fixed. Pls try this

**Comment by techroy23** [comment]
HI i updated my code 
```

<head>
<link href="papaya.js" rel="preload" as="script">
</head>
<body>
<div id="papaya" data-status="false" data-locale="en" data-height="100%" data-width="100%" data-link="magnet:?xt=urn:btih:3WBFL3G4PSSV7MF37AJSHWDQMLNR63I4"></div>
<script src="papaya.js"></script>
</body>
```

but it still shows ru.
even after making a local  copies of the 77a9c5848d7426f536de6c94ab19d2d2d03f0249.

**Comment by Papayaplayer** [comment]
Hi! We fixed this today. Try it
